version: "2"

formatters:
  enable:
    - goimports

linters:
  default: none
  enable:
    - revive
    - errcheck
    - gocognit
    - govet
    - ineffassign
    - staticcheck
    - unused

  exclusions:
    presets:
      - comments