name: Pull Request Sanity Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.3.1
          args: --timeout=3m

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker build -t vibed-traveller:test .
          
      - name: Verify image was created
        run: |
          docker images | grep vibed-traveller
          docker run --rm vibed-traveller:test echo "Docker image is working correctly"
