name: Docker Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker build -t vibed-traveller:test .
          
      - name: Verify image was created
        run: |
          docker images | grep vibed-traveller
          docker run --rm vibed-traveller:test echo "Docker image is working correctly"
